# GitHub Issue 创建页面配置
# 参考: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: true

contact_links:
#  - name: ❓ 提问与讨论
#    url: https://github.com/KylinShinlyLin/QozeCode/discussions
#    about: 如果你有问题、使用困惑或想发起讨论，请前往 Discussions 区

  - name: 📖 项目文档
    url: https://github.com/KylinShinlyLin/QozeCode/blob/main/README.md
    about: 查看 README 了解项目介绍、安装和使用方法
